version = 0.1
[default.deploy.parameters]
stack_name = "sd-china"
resolve_s3 = true
s3_prefix = "sd-china"
region = "cn-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DDBTableName=\"AIGC_CONFIG_2\" CloudfrontCNAME=\"stable-diffusion-beta.tiangeli.a2z.org.cn\""
image_repositories = []
